# Generated by Django 2.2.4 on 2019-10-10 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0003_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Waifus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='favorito',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='friends',
        ),
        migrations.AddField(
            model_name='usuario',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='inventario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='amigos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prueba.Friends'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prueba.Waifus'),
        ),
    ]
