# Generated by Django 3.0.1 on 2020-01-13 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0005_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
