# Generated by Django 3.0.1 on 2020-01-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0009_auto_20200115_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='cover',
            field=models.ImageField(upload_to='perfil/profile_pics'),
        ),
    ]
